# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/silvere/Work/Tuto/STM32_Projects/Libopencm3_projects/STM32_Project_Template

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/silvere/Work/Tuto/STM32_Projects/Libopencm3_projects/STM32_Project_Template

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/silvere/Work/Tuto/STM32_Projects/Libopencm3_projects/STM32_Project_Template/CMakeFiles /home/silvere/Work/Tuto/STM32_Projects/Libopencm3_projects/STM32_Project_Template//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/silvere/Work/Tuto/STM32_Projects/Libopencm3_projects/STM32_Project_Template/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named libopencm3_project

# Build rule for target.
libopencm3_project: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libopencm3_project
.PHONY : libopencm3_project

# fast build rule for target.
libopencm3_project/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libopencm3_project.dir/build.make CMakeFiles/libopencm3_project.dir/build
.PHONY : libopencm3_project/fast

#=============================================================================
# Target rules for targets named RE46C109_Programmer.elf

# Build rule for target.
RE46C109_Programmer.elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RE46C109_Programmer.elf
.PHONY : RE46C109_Programmer.elf

# fast build rule for target.
RE46C109_Programmer.elf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RE46C109_Programmer.elf.dir/build.make CMakeFiles/RE46C109_Programmer.elf.dir/build
.PHONY : RE46C109_Programmer.elf/fast

#=============================================================================
# Target rules for targets named flash

# Build rule for target.
flash: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flash
.PHONY : flash

# fast build rule for target.
flash/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash.dir/build.make CMakeFiles/flash.dir/build
.PHONY : flash/fast

drivers/RE46C109/RE46C109_drv.obj: drivers/RE46C109/RE46C109_drv.c.obj
.PHONY : drivers/RE46C109/RE46C109_drv.obj

# target to build an object file
drivers/RE46C109/RE46C109_drv.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RE46C109_Programmer.elf.dir/build.make CMakeFiles/RE46C109_Programmer.elf.dir/drivers/RE46C109/RE46C109_drv.c.obj
.PHONY : drivers/RE46C109/RE46C109_drv.c.obj

drivers/RE46C109/RE46C109_drv.i: drivers/RE46C109/RE46C109_drv.c.i
.PHONY : drivers/RE46C109/RE46C109_drv.i

# target to preprocess a source file
drivers/RE46C109/RE46C109_drv.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RE46C109_Programmer.elf.dir/build.make CMakeFiles/RE46C109_Programmer.elf.dir/drivers/RE46C109/RE46C109_drv.c.i
.PHONY : drivers/RE46C109/RE46C109_drv.c.i

drivers/RE46C109/RE46C109_drv.s: drivers/RE46C109/RE46C109_drv.c.s
.PHONY : drivers/RE46C109/RE46C109_drv.s

# target to generate assembly for a file
drivers/RE46C109/RE46C109_drv.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RE46C109_Programmer.elf.dir/build.make CMakeFiles/RE46C109_Programmer.elf.dir/drivers/RE46C109/RE46C109_drv.c.s
.PHONY : drivers/RE46C109/RE46C109_drv.c.s

drivers/gpio/led_driver.obj: drivers/gpio/led_driver.c.obj
.PHONY : drivers/gpio/led_driver.obj

# target to build an object file
drivers/gpio/led_driver.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RE46C109_Programmer.elf.dir/build.make CMakeFiles/RE46C109_Programmer.elf.dir/drivers/gpio/led_driver.c.obj
.PHONY : drivers/gpio/led_driver.c.obj

drivers/gpio/led_driver.i: drivers/gpio/led_driver.c.i
.PHONY : drivers/gpio/led_driver.i

# target to preprocess a source file
drivers/gpio/led_driver.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RE46C109_Programmer.elf.dir/build.make CMakeFiles/RE46C109_Programmer.elf.dir/drivers/gpio/led_driver.c.i
.PHONY : drivers/gpio/led_driver.c.i

drivers/gpio/led_driver.s: drivers/gpio/led_driver.c.s
.PHONY : drivers/gpio/led_driver.s

# target to generate assembly for a file
drivers/gpio/led_driver.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RE46C109_Programmer.elf.dir/build.make CMakeFiles/RE46C109_Programmer.elf.dir/drivers/gpio/led_driver.c.s
.PHONY : drivers/gpio/led_driver.c.s

drivers/memory/mamory.obj: drivers/memory/mamory.c.obj
.PHONY : drivers/memory/mamory.obj

# target to build an object file
drivers/memory/mamory.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RE46C109_Programmer.elf.dir/build.make CMakeFiles/RE46C109_Programmer.elf.dir/drivers/memory/mamory.c.obj
.PHONY : drivers/memory/mamory.c.obj

drivers/memory/mamory.i: drivers/memory/mamory.c.i
.PHONY : drivers/memory/mamory.i

# target to preprocess a source file
drivers/memory/mamory.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RE46C109_Programmer.elf.dir/build.make CMakeFiles/RE46C109_Programmer.elf.dir/drivers/memory/mamory.c.i
.PHONY : drivers/memory/mamory.c.i

drivers/memory/mamory.s: drivers/memory/mamory.c.s
.PHONY : drivers/memory/mamory.s

# target to generate assembly for a file
drivers/memory/mamory.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RE46C109_Programmer.elf.dir/build.make CMakeFiles/RE46C109_Programmer.elf.dir/drivers/memory/mamory.c.s
.PHONY : drivers/memory/mamory.c.s

drivers/systick/systick.obj: drivers/systick/systick.c.obj
.PHONY : drivers/systick/systick.obj

# target to build an object file
drivers/systick/systick.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RE46C109_Programmer.elf.dir/build.make CMakeFiles/RE46C109_Programmer.elf.dir/drivers/systick/systick.c.obj
.PHONY : drivers/systick/systick.c.obj

drivers/systick/systick.i: drivers/systick/systick.c.i
.PHONY : drivers/systick/systick.i

# target to preprocess a source file
drivers/systick/systick.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RE46C109_Programmer.elf.dir/build.make CMakeFiles/RE46C109_Programmer.elf.dir/drivers/systick/systick.c.i
.PHONY : drivers/systick/systick.c.i

drivers/systick/systick.s: drivers/systick/systick.c.s
.PHONY : drivers/systick/systick.s

# target to generate assembly for a file
drivers/systick/systick.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RE46C109_Programmer.elf.dir/build.make CMakeFiles/RE46C109_Programmer.elf.dir/drivers/systick/systick.c.s
.PHONY : drivers/systick/systick.c.s

drivers/timer/timer_drv.obj: drivers/timer/timer_drv.c.obj
.PHONY : drivers/timer/timer_drv.obj

# target to build an object file
drivers/timer/timer_drv.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RE46C109_Programmer.elf.dir/build.make CMakeFiles/RE46C109_Programmer.elf.dir/drivers/timer/timer_drv.c.obj
.PHONY : drivers/timer/timer_drv.c.obj

drivers/timer/timer_drv.i: drivers/timer/timer_drv.c.i
.PHONY : drivers/timer/timer_drv.i

# target to preprocess a source file
drivers/timer/timer_drv.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RE46C109_Programmer.elf.dir/build.make CMakeFiles/RE46C109_Programmer.elf.dir/drivers/timer/timer_drv.c.i
.PHONY : drivers/timer/timer_drv.c.i

drivers/timer/timer_drv.s: drivers/timer/timer_drv.c.s
.PHONY : drivers/timer/timer_drv.s

# target to generate assembly for a file
drivers/timer/timer_drv.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RE46C109_Programmer.elf.dir/build.make CMakeFiles/RE46C109_Programmer.elf.dir/drivers/timer/timer_drv.c.s
.PHONY : drivers/timer/timer_drv.c.s

drivers/uart/uart_drv.obj: drivers/uart/uart_drv.c.obj
.PHONY : drivers/uart/uart_drv.obj

# target to build an object file
drivers/uart/uart_drv.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RE46C109_Programmer.elf.dir/build.make CMakeFiles/RE46C109_Programmer.elf.dir/drivers/uart/uart_drv.c.obj
.PHONY : drivers/uart/uart_drv.c.obj

drivers/uart/uart_drv.i: drivers/uart/uart_drv.c.i
.PHONY : drivers/uart/uart_drv.i

# target to preprocess a source file
drivers/uart/uart_drv.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RE46C109_Programmer.elf.dir/build.make CMakeFiles/RE46C109_Programmer.elf.dir/drivers/uart/uart_drv.c.i
.PHONY : drivers/uart/uart_drv.c.i

drivers/uart/uart_drv.s: drivers/uart/uart_drv.c.s
.PHONY : drivers/uart/uart_drv.s

# target to generate assembly for a file
drivers/uart/uart_drv.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RE46C109_Programmer.elf.dir/build.make CMakeFiles/RE46C109_Programmer.elf.dir/drivers/uart/uart_drv.c.s
.PHONY : drivers/uart/uart_drv.c.s

src/main.obj: src/main.c.obj
.PHONY : src/main.obj

# target to build an object file
src/main.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RE46C109_Programmer.elf.dir/build.make CMakeFiles/RE46C109_Programmer.elf.dir/src/main.c.obj
.PHONY : src/main.c.obj

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RE46C109_Programmer.elf.dir/build.make CMakeFiles/RE46C109_Programmer.elf.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RE46C109_Programmer.elf.dir/build.make CMakeFiles/RE46C109_Programmer.elf.dir/src/main.c.s
.PHONY : src/main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... flash"
	@echo "... libopencm3_project"
	@echo "... RE46C109_Programmer.elf"
	@echo "... drivers/RE46C109/RE46C109_drv.obj"
	@echo "... drivers/RE46C109/RE46C109_drv.i"
	@echo "... drivers/RE46C109/RE46C109_drv.s"
	@echo "... drivers/gpio/led_driver.obj"
	@echo "... drivers/gpio/led_driver.i"
	@echo "... drivers/gpio/led_driver.s"
	@echo "... drivers/memory/mamory.obj"
	@echo "... drivers/memory/mamory.i"
	@echo "... drivers/memory/mamory.s"
	@echo "... drivers/systick/systick.obj"
	@echo "... drivers/systick/systick.i"
	@echo "... drivers/systick/systick.s"
	@echo "... drivers/timer/timer_drv.obj"
	@echo "... drivers/timer/timer_drv.i"
	@echo "... drivers/timer/timer_drv.s"
	@echo "... drivers/uart/uart_drv.obj"
	@echo "... drivers/uart/uart_drv.i"
	@echo "... drivers/uart/uart_drv.s"
	@echo "... src/main.obj"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

